### ISSUE TITLE
rx_shared_preferences-2.0.0-nullsafety.0

### ISSUE THREAD

**Issue by tvtrong** [hoc081098/rx_shared_preferences#17]
error G76A9B1F6: The method 'containsKey' isn't defined for the class 'SharedPreferences'.
error G76A9B1F6: The method 'reload' isn't defined for the class 'SharedPreferences'.

**Comment by tvtrong** [comment]
/C:/Users/rqsrd/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/rx_shared_preferences-2.0.0-nullsafety.0/lib/src/impl/shared_preferences_adapter.dart(24,20): error G76A9B1F6: The method 'containsKey' isn't defined for the class 'SharedPreferences'. [E:\UNIVERSE\APPS\flutter_bloc_rxdart\build\windows\flutter\flutter_assemble.vcxproj]
/C:/Users/rqsrd/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/rx_shared_preferences-2.0.0-nullsafety.0/lib/src/impl/shared_preferences_adapter.dart(28,19): error G76A9B1F6: The method 'reload' isn't defined for the class 'SharedPreferences'. [E:\UNIVERSE\APPS\flutter_bloc_rxdart\build\windows\flutter\flutter_assemble.vcxproj]
Building Windows application...
Exception: Build process failed.

**Comment by hoc081098** [comment]
Everything are working well. You can checkout example https://github.com/hoc081098/rx_shared_preferences/blob/master/example/pubspec.yaml
