### ISSUE TITLE
Latest Version

### ISSUE THREAD

**Issue by moinkhan780** [hoc081098/rx_shared_preferences#59]
Please update the package to latest version
Thanks

**Comment by hoc081098** [comment]
Hi @moinkan780, 
Do you have a problem with dependency versions?

**Comment by moinkhan780** [comment]
@hoc081098  No issue. its working perfectly in many of my applications. but i think may be its required to be update time to time.

Thank you!

**Comment by hoc081098** [comment]
@moinkhan780 i will look at it 😂

_Sent from my 2201117TG using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
